---
title: "nic_demo"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


# Introduction

My attempt to understand and reproduce the work done in the synthpop repo by j4sonli.

# Set up Environment

^ Only need to run once
```{r}
# 1. Initialise a renv in the project directory, you can check 
# it's created in your local machine by running `.libPaths()`
# renv::init()

# 2. Install the packages j4sonli recommended in his README
# renv::install(c(c("dplyr","tidyr","stringr","R.utils","tidycensus","bnlearn","foreach","doSNOW","ggplot2")))

# 3. Update your lockfile
renv::snapshot()
```

# Load Libraries
```{r}
library(glue)
library(config)
library(dplyr)
library(ggplot2)
```


```{r}
# Test getting api key from config file
# Install if necessary: install.packages("config")
cfg <- config::get()
us_census_api_key <- cfg$us_census_api_key
```

```{r}
# Rscript synthpop.R -puma=<XXYYYYY> [-use_prev_marg] [-marg_dir=<"some/path/">] [-samp_rate=<num>] [-suffix=<"abcdefg">] [-ncores=<num>]

name <- "Eric"
age <- 42
message <- glue('Hello, {name}. You are {age}.')
#> Hello, Eric. You are 42.
```

```{r}
# Base R dataset excludes DC and territories, so we build the full list cleanly:
state_fips <- data.frame(
  state_name = c(
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
    "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", 
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", 
    "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", 
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", 
    "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", 
    "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", 
    "Washington", "West Virginia", "Wisconsin", "Wyoming"
  ),
  state_abb = c(
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", 
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", 
    "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", 
    "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", 
    "UT", "VT", "VA", "WA", "WV", "WI", "WY"
  ),
  state_code = c(
    "01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "13", 
    "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", 
    "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", 
    "37", "38", "39", "40", "41", "42", "44", "45", "46", "47", "48", 
    "49", "50", "51", "53", "54", "55", "56"
  ),
  stringsAsFactors = FALSE
)

# Preview the dataframe
```


```{r}
puma_df <- read.csv("synthpop_data/2010_Census_Tract_to_2010_PUMA.csv")
GA_puma_df <- puma_df[puma_df$STATEFP == FIPS_state_code,]
GA_puma_codes <- (GA_puma_df %>%
  group_by(STATEFP, PUMA5CE) %>%
  summarise(count = n()))$PUMA5CE
unique(GA_puma_codes)
```


```{r}
# Federal Information Processing Standard (Federal Information Processing Standard), two-digit numeric ids for US states
STATE_NAME <- "Georgia"
COUNTY_FP <- 121 # Fulton county, where Georgia Tech is
PUMA_CODE <- GA_puma_codes[1]
FIPS_STATE_CODE <- state_fips[state_fips$state_name == STATE_NAME,]$state_code
```


# Exploring the sample output datasets

```{r}
output_cambridge_hhs <- read.csv("./synthpop_output/2503302/syn_hhs_spatial_2503302-example.csv")

head(output_cambridge_hhs)
```

```{r}
unique(output_cambridge_hhs$tenur)

# for (name in names(output_cambridge_hhs)) { 
#   print(name)
# }

unique(output_cambridge_hhs$HHID)
unique(output_cambridge_hhs$tenur)
unique(output_cambridge_hhs$hhinc)
unique(output_cambridge_hhs$nwork)
unique(output_cambridge_hhs$ncars)
unique(output_cambridge_hhs$nchil)
unique(output_cambridge_hhs$hhsiz)
unique(output_cambridge_hhs$true_hhsiz)
unique(output_cambridge_hhs$true_nwork)
unique(output_cambridge_hhs$true_nchil)
unique(output_cambridge_hhs$hhtype)
unique(output_cambridge_hhs$puma)
unique(output_cambridge_hhs$i_age)
unique(output_cambridge_hhs$i_sex)
unique(output_cambridge_hhs$race_)
unique(output_cambridge_hhs$i_eth)
unique(output_cambridge_hhs$i_inc)
unique(output_cambridge_hhs$emply)
unique(output_cambridge_hhs$indus)
unique(output_cambridge_hhs$edu_q)
unique(output_cambridge_hhs$tenur_prox)
```

```{r}
typeof(names(output_cambridge_hhs))
```

```{r}
intersected_colnames <- intersect(colnames(output_cambridge_hhs), colnames(output_fulton_hhs))
```

```{r}
for (colnames in intersected_colnames) {
  print(colnames)
}
```


```{r}
library(DataExplorer)
create_report(output_cambridge_hhs)
```


# Fulton County, Georgia

Where Atlanta is located

```{r}
output_fulton_hhs <- read.csv("./synthpop_output/1300100/syn_hhs_1300100.csv")
head(output_fulton_hhs, 5)
```

```{r}
dim(output_fulton_hhs)
```

```{r}
dim(output_cambridge_hhs)
```



```{r}
create_report(output_fulton_hhs)
```


# Maps

```{r}
base_path <- "synthpop_data/acs_marginals"

org_map_pumas <- c("0603701", "0603716", "0603733",
               "4805000", "4804901", "4804614",
               "0400134", "0400105", "0400122",
               "2501400", "2503603", "2503302",
               "1208900", "1203105", "1203103",
               "5600200", "5600100", "5600300", "5600400", "5600500")


for (map_puma in org_map_pumas) {
  # Dynamically construct the path: "synthpop_data/acs_marginals/0603701"
  full_puma_dir <- file.path(base_path, map_puma)
  
  if (!dir.exists(full_puma_dir)) {
    dir.create(full_puma_dir, recursive = TRUE, showWarnings = FALSE)
    cat("Initialized folder:", full_puma_dir, "\n")
  }
}
```


```{r}
prepare_data_file <- "prepare_data.R"
process_pums_file <- "process_pums.R"
process_marg_file <- "process_marg.R"
train_bns_file <- "train_bns.R"
sample_hhs_file <- "sample_hhs.R"
sample_indvs_file <- "sample_indvs.R"
select_synpop_file <- "select_synpop.jl"
assign_spatial_file <- "assign_spatial.jl"
puma_tract_equiv_file <- "synthpop_data/2010_Census_Tract_to_2010_PUMA.csv"
tract_block_equiv_file <- "synthpop_data/tract_block_equiv_2010.Rds"
my_census_api_key <- US_CENSUS_API_KEY

pumas <- org_map_pumas
source("prepare_data.R")
```

```{r}
options(box.path = getwd())
```



```{r}
box::use(./plot_maps[...])

# Load functions from `plot_map.R`
# Pass the key variable directly to the active session (do not try to install it globally)
# tidycensus::census_api_key(my_census_api_key)
# Sys.setenv(CENSUS_API_KEY = my_census_api_key)
# Explicitly propagate it to the system environment so child processes (system() calls) can see it
# source("plot_maps.R")
source("sum.R")

FULTON_PUMA_CODE <- 1300100
CAMBRIDGE_PUMA_CODE <- 2503302
map_pumas <- c(FULTON_PUMA_CODE, CAMBRIDGE_PUMA_CODE)

plot_study_area(map_pumas)

```


```{r}
org_map_pumas <- c("0603701", "0603716", "0603733",
               "4805000", "4804901", "4804614",
               "0400134", "0400105", "0400122",
               "2501400", "2503603", "2503302",
               "1208900", "1203105", "1203103",
               "5600200", "5600100", "5600300", "5600400", "5600500")
for (org_puma in org_map_pumas) {
  command <- glue('Rscript synthpop_truncated.R -puma={org_puma}')
  print(command)
}


```







